# Generated by Django 4.1.2 on 2022-10-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("job", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="show_description", new_name="short_description"
        )
    ]
